import React,{useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {Cloud,Upload,ArrowLeft,Image,Video,Music,Film,X,Plus} from 'lucide-react';
import {store,ancestors} from './store.js';
import {uploadFile} from './media.js';
import {createUploadGate} from './workspace-context.js';
import {freestyleRoles,freestyleInputIds,uploadFreestyleFiles} from './media-operations.js';
import AssetPreview from './AssetPreview.jsx';
import CandidateReview from './CandidateReview.jsx';
import ReferenceEditor from './ReferenceEditor.jsx';
import {removeFreestyleInput} from './cloud-model.js';
import {navigateWorkspace} from './workspace-navigation.js';
import {CloudButton,CloudProjects,CloudWorkspaceBar,CloudShotPanel,useCloud} from './CloudStudio.jsx';
import {cloudController as cloud} from './cloud-controller.js';
import './freestyle.css';
import {ServiceStatus} from './ServiceStatus.jsx';

const run=promise=>promise.catch(()=>{}),names={image:'图片',video:'视频',audio:'音频'},icons={image:Image,video:Video,audio:Music};
function ProjectDialog({onClose}){const ref=useRef(),opener=useRef(document.activeElement);useEffect(()=>{const element=ref.current;element.showModal();element.querySelector('input:not([type=file])')?.focus();return()=>{element.close();opener.current?.isConnected&&opener.current.focus();};},[]);return <dialog className="modal wide" ref={ref} aria-label="快速创作 · 云项目与账户" onCancel={e=>{e.preventDefault();onClose();}}><div className="modal-heading"><h2>云项目与账户</h2><button className="icon-button" aria-label="关闭云项目窗口" onClick={onClose}><X size={18}/></button></div><CloudProjects onClose={onClose} quick/></dialog>;}

function InputZone({project,shot,kind,role,title,description,maximum=1,disabled=false,guide=false}){
  const ref=useRef(),uploadGate=useRef(createUploadGate()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dragging,setDragging]=useState(false),Icon=icons[kind]||Film;
  const roles=freestyleRoles(kind,role),ids=freestyleInputIds(project,shot.id,{kind,role,guide}),assets=[...new Set(ids)].map(id=>project.entities.find(e=>e.id===id)).filter(Boolean),count=ids.length;
  async function accept(files){if(uploadGate.current.busy){setError('这一区域正在保存素材，请完成后再添加。');return;}setError('');if(disabled){setError('先读取服务能力并切换到此输入对应的生成方式。现有素材会保留。');return;}if(!files.length)return;await uploadGate.current.run(async()=>{setBusy(true);try{await uploadFreestyleFiles({store,shotId:shot.id,files,kind,role,guide,maximum,upload:uploadFile});}catch(e){setError(e.message);}finally{setBusy(false);if(ref.current)ref.current.value='';}});}

  return <section className={'freestyle-zone '+(disabled?'is-disabled ':'')+(dragging?'is-dragging':'')} aria-label={title} onDragOver={event=>{event.preventDefault();if(!disabled&&!uploadGate.current.busy)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);accept([...event.dataTransfer.files]);}}><header><Icon size={19}/><h3>{title}</h3><span>{count}/{maximum}</span></header><p>{description}</p><input ref={ref} type="file" tabIndex={-1} disabled={disabled||busy||count>=maximum} className="visually-hidden" aria-label={'上传'+title} multiple={maximum>1} accept={kind?kind+'/*':'image/*,video/*,audio/*'} onChange={event=>accept([...event.target.files])}/><button type="button" className="freestyle-upload" disabled={disabled||busy||count>=maximum} onClick={()=>ref.current.click()}><Upload size={17}/>{busy?'正在上传与核验…':`拖到这里，或选择${kind?names[kind]:'文件'}`}</button>{error&&<p className="cloud-error" role="alert">{error}</p>}<div className="freestyle-inputs">{assets.map(asset=><article key={asset.id}><AssetPreview entity={asset}/><div><b>{asset.title}</b><small>{names[asset.type]}{asset.data.metadata?.duration?` · ${Number(asset.data.metadata.duration).toFixed(1)} 秒`:''}</small><button type="button" disabled={busy} onClick={()=>store.editProject(p=>removeFreestyleInput(p,shot.id,asset.id,{guide,roles}))}>{guide?'移除该素材所有锚点':'移除此区域关联'}</button></div></article>)}</div>{guide&&assets.length>0&&<p>当前锚点默认在 0 秒；在右侧“高级控制 → 时间锚点”调整时刻、声音和原片选段。</p>}</section>;
}

export default function Freestyle(){
  const state=useSyncExternalStore(store.subscribe,store.getState,store.getState),c=useCloud(),[dialog,setDialog]=useState(false),[shotId,setShotId]=useState(''),project=state.project,cloudMode=state.workspace.mode==='cloud',shots=cloudMode?project.entities.filter(e=>e.type==='shot'):[],shot=shots.find(e=>e.id===shotId)||shots[0],recipe=c.capabilities?.recipes?.find(r=>r.id===shot?.data.h3?.recipeId)||c.capabilities?.recipes?.[0],mode=recipe?.mode,clipLimits=recipe?.limits?`${recipe.limits.min_clip_duration}–${recipe.limits.max_clip_duration} 秒`: '以服务声明为准';
  const open=()=>setDialog(true);const newQuick=()=>{if(!c.account){open();return;}run(cloud.createQuick());};
  useEffect(()=>{document.title='映序 · 快速视频创作';},[]);
  useEffect(()=>{if(!state.notice)return;const timer=setTimeout(()=>store.notify(''),5500);return()=>clearTimeout(timer);},[state.notice]);
  return <div className="freestyle-shell"><a className="skip" href="#freestyle-main">跳到创作区</a><header className="freestyle-top"><a href="/" onClick={e=>navigateWorkspace(e,'/')} className="freestyle-brand"><span>Ⅱ</span><b>映序</b><small>快速创作</small></a><nav aria-label="快速创作导航"><a href="/" onClick={e=>navigateWorkspace(e,'/')}><ArrowLeft size={15}/>短剧工作台</a><CloudButton onOpen={open}/><button disabled={c.busy} onClick={newQuick}><Plus size={15}/>新建快速创作</button></nav></header><CloudWorkspaceBar/><main id="freestyle-main" tabIndex={-1}>
    {!cloudMode||!shot?<section className="freestyle-welcome">{c.account&&<ServiceStatus capabilities={c.capabilities}/>}<span className="eyebrow">ONE IDEA, ONE SHOT</span><h1>把一个想法，拍成一个镜头。</h1><p>写下画面、动作与声音。参考图片、动作视频和音频分别放好，再核对清晰度与时长。</p><div className="freestyle-start-actions"><button className="primary" disabled={c.busy} onClick={newQuick}><Film size={18}/>{c.account?'开始新的快速创作':'登录后开始创作'}</button><button onClick={open}>打开已有云项目</button></div><div className="freestyle-examples"><article><b>只有一句想法</b><p>选择文生视频，写清主体与动作。没有参考也能先预检。</p></article><article><b>让一张图片动起来</b><p>图片放首帧，描述接下来发生什么；尾帧按需添加。</p></article><article><b>人物配上动作与声音</b><p>选择全能参考，分别放角色图、动作片段和音频。</p></article></div><p className="muted">新建只保存项目，不提交模型请求。本机作品保留在短剧工作台。</p>{cloudMode&&!shot&&<p className="cloud-warning">当前项目还没有镜头。可回短剧工作台添加，或新建快速创作项目。</p>}{c.error&&<p className="cloud-error" role="alert">{c.error}</p>}</section>:<><div className="freestyle-heading"><div><span className="eyebrow">QUICK VIDEO</span><h1>{project.title}</h1><p>① 准备输入　② 预检参数　③ 确认排队　④ 选择结果</p></div>{shots.length>1&&<label>当前镜头<select value={shot.id} onChange={e=>setShotId(e.target.value)}>{shots.map(s=><option key={s.id} value={s.id}>{ancestors(project,s.id).map(e=>e.title).join(' / ')} / {s.title}</option>)}</select></label>}</div>{project.journey?.workspace!=='freestyle'&&<p className="cloud-warning">正在单镜编辑短剧项目。章节结构、其他镜头与已采用版本都会保留。</p>}
    <div className="freestyle-grid"><section className="freestyle-reference-column" aria-label="分别放置参考素材"><div className="freestyle-input-heading"><h2>把参考放对位置</h2><p>{!recipe?'正在等待服务能力；暂不接受新输入。':mode==='fl'?'当前文生 / 首尾帧模式：可完全不放素材，或只指定开头与结尾。':'当前全能参考模式：分别放图片、视频和音频，至少一份参考。'}</p></div><div className="freestyle-zone-grid"><InputZone project={project} shot={shot} kind="image" role="firstFrame" title="首帧图片" description="视频从这一画面出发。" disabled={mode!=='fl'}/><InputZone project={project} shot={shot} kind="image" role="lastFrame" title="尾帧图片" description="希望最后落在的画面，可留空。" disabled={mode!=='fl'}/></div><InputZone project={project} shot={shot} kind="image" role="reference" title="图片参考" description="人物、服装、物体或风格；在提示词中说明每张图的用途。" maximum={recipe?.limits?.max_images??0} disabled={mode!=='ref'}/><InputZone project={project} shot={shot} kind="video" role="motion" title="视频 / 动作参考" description={`动作与运镜示范。有效片段长度 ${clipLimits}，长片请先选段。`} maximum={recipe?.limits?.max_videos??0} disabled={mode!=='ref'}/><InputZone project={project} shot={shot} kind="audio" role="audio" title="音频参考" description="对白、音色或声音节奏，与最终剪辑背景音乐分开。" maximum={recipe?.limits?.max_audios??0} disabled={mode!=='ref'}/><details className="freestyle-guide-section"><summary>需要在某个时刻指定画面或声音？</summary><InputZone project={project} shot={shot} title="时间锚点素材" description="上传后默认放在 0 秒。高级控制中可选原片范围和调整时刻。" maximum={recipe?.limits?.max_guides??0} disabled={!recipe} guide/></details><details className="freestyle-reference-details"><summary>复用已有素材 · 设置视频 / 音频选段</summary><ReferenceEditor project={project} shotId={shot.id}/></details><p className="muted">切换生成方式会保留已上传输入；不兼容的关联必须先明确移除。移除关联不删除原文件。</p></section><aside className="freestyle-controls" aria-label="提示词与生成设置"><CloudShotPanel key={shot.id} project={project} shot={shot}/></aside></div>
    <section className="freestyle-results" aria-label="生成结果与返修"><h2>选择结果，再决定怎么改</h2><p>结果不会自动替换你的选择。先看效果，再明确保留什么、只改什么。</p><CandidateReview project={project} shots={shots} currentShot={shot} onChooseShot={setShotId} onInspect={()=>document.querySelector('.freestyle-controls')?.scrollIntoView({behavior:'smooth'})} onReferences={()=>document.querySelector('.freestyle-reference-column')?.scrollIntoView({behavior:'smooth'})}/></section></>}
  </main>{dialog&&<ProjectDialog onClose={()=>setDialog(false)}/>}<div className={'toast '+(state.notice?'show':'')} role="status" aria-live="polite">{state.notice}</div></div>;
}
