"""Explicit private local backups. No import-time IO, credentials, or services.

Only published media referenced by the consistent DB snapshot are copied. Live
auth tables, sessions, runtime files, environment, and arbitrary directories are
never exported. Recovery is an isolated, disabled copy, not automatic failover.
"""
from __future__ import annotations

import csv
from contextlib import closing
import hashlib
import io
import json
import os
from pathlib import Path
import re
import sqlite3
import stat
import subprocess
import time
from urllib.parse import urlsplit, parse_qs, unquote

from sqlalchemy import create_engine, text, JSON
from sqlalchemy.engine import URL

from .storage import LocalObjectStore, _check_ancestors, _no_links, _copy, _sync_directory, key_belongs_to

MIB = 1024*1024
AUTH_TABLES = frozenset({"platform_accounts", "platform_sessions", "platform_service_clients", "platform_login_limits"})


class BackupError(Exception):
    """Stable code only; never attach DB URLs, subprocess output, or secrets."""


def _schemas():
    from .repository import metadata
    from .assets import metadata as assets
    from .storage_asset_journal import _schema as quota
    from .storage_multipart import _metadata as multipart
    from .artifact_writer import _schema as writer
    from .batches import metadata as batches
    return (metadata, assets, quota, multipart, writer, batches)


def _tables():
    return {table.name: table for schema in _schemas() for table in schema.sorted_tables}


def _absolute(path):
    path = Path(path)
    if not path.is_absolute() or ".." in path.parts:
        raise BackupError("backup_paths_must_be_explicit_absolute")
    _check_ancestors(path)
    return path


def _regular(path, *, max_bytes=None):
    path = _absolute(path)
    info = _no_links(path)
    if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or (max_bytes is not None and info.st_size > max_bytes):
        raise BackupError("backup_file_type_or_size_invalid")
    return path


def _private_new_directory(path):
    path = _absolute(path)
    if path.exists() or path.is_symlink() or not path.parent.is_dir():
        raise BackupError("backup_target_must_be_a_new_directory_under_an_existing_parent")
    path.mkdir(mode=0o700)
    if os.name == "nt":
        try:
            result = subprocess.run(["whoami", "/user", "/fo", "csv", "/nh"], capture_output=True, text=True,
                                    timeout=10, check=True, creationflags=subprocess.CREATE_NO_WINDOW)
            sid = list(csv.reader(io.StringIO(result.stdout)))[0][1]
            if not re.fullmatch(r"S-1-(?:\d+-)+\d+", sid):
                raise ValueError
            subprocess.run(["icacls", str(path), "/inheritance:r", "/grant:r",
                            "*"+sid+":(OI)(CI)F", "*S-1-5-18:(OI)(CI)F"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10, check=True,
                           creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception:
            raise BackupError("backup_private_windows_acl_failed") from None
    else:
        path.chmod(0o700)
        info = path.stat()
        if info.st_mode & 0o077 or info.st_uid != os.getuid():
            raise BackupError("backup_private_permissions_failed")
    return path


def _write_json(path, value):
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, allow_nan=False).encode("utf-8")
    if len(encoded) > 16*MIB:
        raise BackupError("backup_manifest_too_large")
    with path.open("xb") as handle:
        if os.name != "nt":
            os.fchmod(handle.fileno(), 0o600)
        handle.write(encoded)
        handle.flush()
        os.fsync(handle.fileno())


def _digest(path):
    digest = hashlib.sha256()
    with _regular(path).open("rb") as source:
        for block in iter(lambda: source.read(MIB), b""):
            digest.update(block)
    return digest.hexdigest()


def _open_sqlite_readonly(path):
    db = sqlite3.connect(_regular(path, max_bytes=256*MIB).as_uri()+"?mode=ro", uri=True, timeout=5)
    db.execute("PRAGMA trusted_schema=OFF")
    db.execute("PRAGMA query_only=ON")
    return db


def _check_db(db, *, published=False):
    objects = dict(db.execute("SELECT name,type FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'"))
    tables = _tables()
    allowed_names = set(tables) | (set() if published else AUTH_TABLES)
    # Indexes are generated by the trusted schema below; reject user triggers/views.
    actual_tables = {name for name, kind in objects.items() if kind == "table"}
    if actual_tables-allowed_names or any(kind in ("trigger", "view") for kind in objects.values()):
        raise BackupError("backup_database_schema_requires_review")
    if not {"platform_jobs", "platform_assets", "platform_artifacts"}.issubset(actual_tables):
        raise BackupError("backup_is_not_platform_database")
    for name in actual_tables & set(tables):
        columns = [row[1] for row in db.execute('PRAGMA table_info("'+name+'")')]
        if columns != [column.name for column in tables[name].columns]:
            raise BackupError("backup_database_version_mismatch")
    if db.execute("PRAGMA quick_check").fetchone() != ("ok",):
        raise BackupError("backup_database_integrity_failed")
    return actual_tables


def _snapshot(source_path, *, timeout_s=60):
    source = _open_sqlite_readonly(source_path)
    memory = sqlite3.connect(":memory:")
    memory.execute("PRAGMA temp_store=MEMORY")
    deadline = time.monotonic()+timeout_s
    try:
        def progress(status, remaining, total):
            if time.monotonic() > deadline or total*source.execute("PRAGMA page_size").fetchone()[0] > 256*MIB:
                raise BackupError("backup_snapshot_size_or_time_limit")
        source.backup(memory, pages=128, progress=progress, sleep=.01)
        _check_db(memory)
        return memory
    except Exception:
        memory.close()
        raise
    finally:
        source.close()


def _create_business_schema(destination):
    # Called only for a new private output/restoration file. Never migrates a
    # source DB; creates missing current-version tables with safe empty defaults.
    engine = create_engine("sqlite:///"+destination.as_posix(), hide_parameters=True)
    try:
        with engine.begin() as connection:
            for schema in _schemas():
                schema.create_all(connection)
    finally:
        engine.dispose()
    if os.name != "nt":
        destination.chmod(0o600)


def _export_business_db(snapshot, destination):
    # Build trusted fresh tables, then copy only their explicit columns. The
    # source auth pages never reach any output file (not even a temporary DB).
    _create_business_schema(destination)
    target = sqlite3.connect(destination)
    counts = {}
    try:
        existing = _check_db(snapshot)
        for name, table in _tables().items():
            if name not in existing:
                counts[name] = 0
                continue
            columns = ",".join('"'+c.name+'"' for c in table.columns)
            select_sql = 'SELECT '+columns+' FROM "'+name+'"'
            insert_sql = 'INSERT INTO "'+name+'" ('+columns+') VALUES ('+','.join('?' for _ in table.columns)+')'
            count = 0
            cursor = snapshot.execute(select_sql)
            while batch := cursor.fetchmany(200):
                target.executemany(insert_sql, batch)
                count += len(batch)
            counts[name] = count
        target.commit()
        if target.execute("PRAGMA foreign_key_check").fetchone() is not None:
            raise BackupError("backup_database_reference_integrity_failed")
        _check_db(target, published=True)
    finally:
        target.close()
    return counts


def _media_references(db):
    found, pending = {}, 0
    def add(owner, info, reference):
        key, size, sha, mime = info.get("key", info.get("object_key")), info.get("size_bytes"), info.get("sha256"), info.get("content_type")
        if (not isinstance(key, str) or not key_belongs_to(key, owner) or type(size) is not int or not 0 < size <= 512*MIB
                or not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{64}", sha)
                or not isinstance(mime, str) or len(mime) > 128 or info.get("provider", "local") != "local"):
            raise BackupError("backup_media_reference_requires_review")
        item = dict(key=key, size_bytes=size, sha256=sha, content_type=mime, owner=owner)
        if key in found and any(found[key][k] != value for k, value in item.items()):
            raise BackupError("backup_media_reference_conflict")
        entry = found.setdefault(key, dict(item, references=[]))
        entry["references"].append(reference)
    for ident, owner, project, status, raw in db.execute("SELECT id,owner,project_id,status,record FROM platform_assets"):
        record = json.loads(raw)
        if status != "ready":
            pending += 1
        for role in ("original", "model"):
            if record.get(role):
                add(owner, record[role], {"table": "assets", "id": ident, "project_id": project, "role": role})
    for ident, owner, project, raw in db.execute("SELECT a.id,j.owner_id,j.project_id,a.metadata FROM platform_artifacts a JOIN platform_jobs j ON j.id=a.job_id"):
        spec = json.loads(raw)
        if spec.get("validated") is not True:
            raise BackupError("backup_artifact_not_validated")
        add(owner, spec, {"table": "artifacts", "id": ident, "project_id": project, "role": spec["kind"]})
    return found, pending


def _publish_media_backup(output, object_root, references, pending, counts, *, source_database):
    media = output/"media"
    media.mkdir(mode=0o700)
    store = LocalObjectStore(object_root)
    objects = []
    for key, item in sorted(references.items()):
        info = store.stat(key)
        if (info.size_bytes, info.sha256, info.content_type) != (item["size_bytes"], item["sha256"], item["content_type"]):
            raise BackupError("backup_object_metadata_mismatch")
        filename = hashlib.sha256(key.encode("ascii")).hexdigest()+".bin"
        with store.open(key) as source, (media/filename).open("xb") as target:
            if os.name != "nt":
                os.fchmod(target.fileno(), 0o600)
            size, sha = _copy(source, target, item["size_bytes"], item["sha256"])
            if size != item["size_bytes"]:
                raise BackupError("backup_object_size_mismatch")
            target.flush()
            os.fsync(target.fileno())
        objects.append(dict(item, file=filename))
    manifest = dict(version=1, kind="sixnine-local-business-backup", created_at=time.time(),
        source_database=source_database, restoration_target="isolated-sqlite-and-local-objects",
        database_sha256=_digest(output/"database.sqlite3"), tables=counts, objects=objects,
        media_bytes=sum(item["size_bytes"] for item in objects), pending_assets=pending,
        excluded=list(sorted(AUTH_TABLES)), staging_included=False, orphan_objects_included=False,
        execution_restore="hold", native_postgres_restore=False)
    _write_json(output/"manifest.json", manifest)  # Success marker written last.
    _sync_directory(media)
    _sync_directory(output)
    return {"state": "backed_up", "objects": len(objects), "media_bytes": manifest["media_bytes"], "pending_assets": pending}


def backup_local(database, object_root, destination, *, max_media_bytes=40*1024*MIB):
    """Explicit read-only source; creates one NEW private backup directory."""
    database, object_root, destination = _absolute(database), _absolute(object_root), _absolute(destination)
    if type(max_media_bytes) is not int or max_media_bytes < 1:
        raise BackupError("backup_media_limit_invalid")
    if not (object_root/"objects").is_dir() or not (object_root/"staging").is_dir():
        raise BackupError("backup_local_object_root_missing")
    if destination.is_relative_to(object_root) or destination == database.parent:
        raise BackupError("backup_destination_overlaps_live_storage")
    snapshot = _snapshot(database)
    try:
        references, pending = _media_references(snapshot)
        total = sum(item["size_bytes"] for item in references.values())
        if len(references) > 100000 or total > max_media_bytes:
            raise BackupError("backup_media_limit_exceeded")
        output = _private_new_directory(destination)
        counts = _export_business_db(snapshot, output/"database.sqlite3")
        return _publish_media_backup(output, object_root, references, pending, counts, source_database="sqlite")
    except BackupError:
        raise
    except Exception:
        raise BackupError("backup_failed_incomplete_directory_kept") from None
    finally:
        snapshot.close()


def _export_postgres_business_db(engine, destination, *, schema="public", timeout_s=60):
    """One read-only PG snapshot; copy ONLY trusted business columns to SQLite."""
    if engine.dialect.name != "postgresql" or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,62}", schema):
        raise BackupError("backup_postgres_source_invalid")
    if type(timeout_s) is not int or not 1 <= timeout_s <= 600:
        raise BackupError("backup_postgres_timeout_invalid")
    trusted = _tables()
    deadline, byte_total, counts = time.monotonic()+timeout_s, 0, {}
    _create_business_schema(destination)
    target = create_engine("sqlite:///"+destination.as_posix(), echo=False, hide_parameters=True)
    try:
        with engine.connect().execution_options(isolation_level="REPEATABLE READ") as source, source.begin():
            source.exec_driver_sql("SET TRANSACTION READ ONLY")
            source.exec_driver_sql("SET LOCAL statement_timeout = "+str(timeout_s*1000))
            source.exec_driver_sql("SET LOCAL lock_timeout = 5000")
            source.exec_driver_sql("SET LOCAL idle_in_transaction_session_timeout = "+str(timeout_s*1000))
            inventory = {name: kind for name, kind in source.execute(text("SELECT table_name,table_type FROM information_schema.tables WHERE table_schema=:schema"), {"schema": schema})}
            require_names = {"platform_jobs", "platform_assets", "platform_artifacts"}
            if (not require_names <= set(inventory) or set(inventory)-set(trusted)-AUTH_TABLES
                    or any(kind != "BASE TABLE" for kind in inventory.values())):
                raise BackupError("backup_database_schema_requires_review")
            columns = {}
            for name, column in source.execute(text("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema=:schema ORDER BY table_name,ordinal_position"), {"schema": schema}):
                columns.setdefault(name, []).append(column)
            with target.begin() as output:
                for name, table in trusted.items():
                    if name not in inventory:
                        counts[name] = 0
                        continue
                    if columns.get(name) != [column.name for column in table.columns]:
                        raise BackupError("backup_database_version_mismatch")
                    relation = '"'+schema+'"."'+name+'"'
                    # Bound a row before fetching it into client memory. The
                    # read-only snapshot is established by the inventory query.
                    count, size, largest = source.execute(text("SELECT count(*),COALESCE(sum(octet_length(row_to_json(t)::text)),0),COALESCE(max(octet_length(row_to_json(t)::text)),0) FROM "+relation+" t")).one()
                    byte_total += int(size)
                    if count > 1000000 or largest > 16*MIB or byte_total > 256*MIB or time.monotonic() > deadline:
                        raise BackupError("backup_snapshot_size_or_time_limit")
                    fields = ",".join('"'+column.name+'"' for column in table.columns)
                    json_nulls = {column.name: "__sixnine_backup_sql_null_"+str(index)
                                  for index, column in enumerate(table.columns) if isinstance(column.type, JSON)}
                    markers = ",".join('"'+name+'" IS NULL AS "'+marker+'"' for name, marker in json_nulls.items())
                    query_fields = fields + ((","+markers) if markers else "")
                    insert_sql = 'INSERT INTO "'+name+'" ('+fields+') VALUES ('+','.join('?' for _ in table.columns)+')'
                    actual = 0
                    with source.execute(text("SELECT "+query_fields+" FROM "+relation).execution_options(stream_results=True, max_row_buffer=200)) as rows:
                        while batch := rows.mappings().fetchmany(200):
                            if time.monotonic() > deadline:
                                raise BackupError("backup_snapshot_size_or_time_limit")
                            # JSON null and SQL NULL both arrive as Python None;
                            # preserve the distinction instead of silently
                            # changing later IS NULL/query behavior on recovery.
                            values = [tuple(json.dumps(row[column.name], ensure_ascii=False, allow_nan=False)
                                      if column.name in json_nulls and not row[json_nulls[column.name]] else row[column.name]
                                      for column in table.columns) for row in batch]
                            output.exec_driver_sql(insert_sql, values)
                            actual += len(batch)
                    if actual != count:
                        raise BackupError("backup_snapshot_count_mismatch")
                    counts[name] = actual
            if destination.stat().st_size > 256*MIB:
                raise BackupError("backup_snapshot_size_or_time_limit")
        with closing(_open_sqlite_readonly(destination)) as db:
            _check_db(db, published=True)
            if db.execute("PRAGMA foreign_key_check").fetchone() is not None:
                raise BackupError("backup_database_reference_integrity_failed")
        return counts
    except BackupError:
        raise
    except Exception:
        raise BackupError("backup_postgres_snapshot_failed_no_details_logged") from None
    finally:
        target.dispose()


def backup_postgres_engine(engine, object_root, destination, *, schema="public", max_media_bytes=40*1024*MIB):
    """Complete PG business + Local media backup; restore target is SQLite.

    The caller supplies an approved in-process engine; never serialize/log it.
    No pg_dump, administrative role or source schema mutation is needed.
    """
    object_root, destination = _absolute(object_root), _absolute(destination)
    if (not (object_root/"objects").is_dir() or not (object_root/"staging").is_dir()
            or destination.is_relative_to(object_root)):
        raise BackupError("backup_local_object_root_missing_or_overlapping")
    if type(max_media_bytes) is not int or max_media_bytes < 1:
        raise BackupError("backup_media_limit_invalid")
    output = _private_new_directory(destination)
    try:
        counts = _export_postgres_business_db(engine, output/"database.sqlite3", schema=schema)
        with closing(_open_sqlite_readonly(output/"database.sqlite3")) as db:
            references, pending = _media_references(db)
        if len(references) > 100000 or sum(item["size_bytes"] for item in references.values()) > max_media_bytes:
            raise BackupError("backup_media_limit_exceeded")
        result = _publish_media_backup(output, object_root, references, pending, counts, source_database="postgresql")
        return {**result, "source_database": "postgresql", "restoration_target": "isolated-sqlite-and-local-objects", "native_postgres_restore": False}
    except BackupError:
        raise
    except Exception:
        raise BackupError("backup_postgres_local_failed_incomplete_directory_kept") from None


def verify_local(directory):
    directory = _absolute(directory)
    try:
        raw = _regular(directory/"manifest.json", max_bytes=16*MIB).read_bytes()
        manifest = json.loads(raw)
        if manifest.get("version") != 1 or manifest.get("kind") != "sixnine-local-business-backup":
            raise BackupError("backup_format_not_supported")
        database = _regular(directory/"database.sqlite3", max_bytes=256*MIB)
        if _digest(database) != manifest["database_sha256"]:
            raise BackupError("backup_database_checksum_mismatch")
        with closing(_open_sqlite_readonly(database)) as db:
            existing = _check_db(db, published=True)
            if db.execute("PRAGMA foreign_key_check").fetchone() is not None:
                raise BackupError("backup_database_reference_integrity_failed")
            references, pending = _media_references(db)
            # An older trusted backup may precede newly added optional tables.
            # Verify its original table set, then create safe empty additions
            # only inside the NEW restoration target.
            counts = {name: db.execute('SELECT count(*) FROM "'+name+'"').fetchone()[0] for name in _tables() if name in existing}
            if counts != manifest.get("tables"):
                raise BackupError("backup_database_counts_mismatch")
        objects = manifest["objects"]
        if not isinstance(objects, list) or len(objects) != len(references) or len(objects) > 100000:
            raise BackupError("backup_manifest_reference_mismatch")
        seen = set()
        for item in objects:
            key = item["key"]
            if key in seen or key not in references:
                raise BackupError("backup_manifest_reference_mismatch")
            seen.add(key)
            expected = references[key]
            if any(item.get(k) != value for k, value in expected.items()):
                raise BackupError("backup_manifest_reference_mismatch")
            filename = hashlib.sha256(key.encode("ascii")).hexdigest()+".bin"
            if item.get("file") != filename:
                raise BackupError("backup_manifest_path_invalid")
            path = _regular(directory/"media"/filename, max_bytes=512*MIB)
            if path.stat().st_size != item["size_bytes"] or _digest(path) != item["sha256"]:
                raise BackupError("backup_media_checksum_mismatch")
        if sum(item["size_bytes"] for item in objects) != manifest["media_bytes"] or pending != manifest["pending_assets"]:
            raise BackupError("backup_manifest_totals_mismatch")
        return manifest
    except BackupError:
        raise
    except Exception:
        raise BackupError("backup_verification_failed") from None


def _quarantine_restored_database(path):
    with closing(sqlite3.connect(path)) as db, db:
        db.execute("PRAGMA trusted_schema=OFF")
        held = []
        for ident, status, raw in db.execute("SELECT id,status,execution_plan FROM platform_jobs").fetchall():
            execution = json.loads(raw)
            execution["enabled"] = False
            if status not in {"succeeded", "failed", "cancelled"}:
                held.append({"job_id": ident, "previous_status": status})
                db.execute("UPDATE platform_jobs SET status='recovery_hold',error_code='disaster_recovery_review_required',fence=fence+1,lease_worker_id=NULL,lease_expires_at=NULL WHERE id=?", (ident,))
            db.execute("UPDATE platform_jobs SET execution_plan=? WHERE id=?", (json.dumps(execution), ident))
        # Plans cannot silently re-enable old execution after account re-provisioning.
        for ident, raw in db.execute("SELECT id,execution_plan FROM platform_plans").fetchall():
            execution = json.loads(raw)
            execution["enabled"] = False
            db.execute("UPDATE platform_plans SET execution_plan=?,expires_at=0 WHERE id=?", (json.dumps(execution), ident))
        db.execute("UPDATE platform_registered_workers SET state='unknown',drain_requested=1,fence=fence+1,expires_at=0 WHERE state!='retired'")
        db.execute("UPDATE platform_registered_devices SET state='unknown' WHERE state!='released'")
        db.execute("UPDATE platform_cpu_slots SET state='unknown'")
        db.execute("UPDATE platform_capacity_gate SET max_instances=0,max_physical_gpus=0")
        db.execute("UPDATE platform_pool_limits SET max_instances=0,max_physical_gpus=0")
        db.execute("UPDATE platform_scaler_leaders SET expires_at=0,fence=fence+1")
        existing = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        if "platform_capacity_approvals" in existing:
            db.execute("UPDATE platform_capacity_approvals SET enabled=0")
        if "platform_capacity_waiters" in existing:
            db.execute("UPDATE platform_capacity_waiters SET state='recovery_hold'")
        # Keep provider IDs/cost reservations and original instance state as evidence.
        # Zero capacity and disabled execution are not claims external billing stopped.
        return held


def restore_local(backup_directory, destination):
    """Restore only to a NEW directory; never accepts or overwrites a live DB."""
    source, destination = _absolute(backup_directory), _absolute(destination)
    if destination.is_relative_to(source):
        raise BackupError("restore_destination_overlaps_backup")
    manifest = verify_local(source)
    target = _private_new_directory(destination)
    try:
        with (source/"database.sqlite3").open("rb") as incoming, (target/"platform.sqlite3").open("xb") as output:
            if os.name != "nt":
                os.fchmod(output.fileno(), 0o600)
            _copy(incoming, output, 256*MIB, manifest["database_sha256"])
            output.flush()
            os.fsync(output.fileno())
        store = LocalObjectStore(target/"objects")
        for item in manifest["objects"]:
            with _regular(source/"media"/item["file"]).open("rb") as body:
                store.put(item["key"], body, content_type=item["content_type"],
                          max_bytes=item["size_bytes"], expected_sha256=item["sha256"])
        _create_business_schema(target/"platform.sqlite3")
        held = _quarantine_restored_database(target/"platform.sqlite3")
        _write_json(target/"RECOVERY-HOLD.json", dict(version=1, execution_enabled=False,
            authentication_reprovision_required=True, held_jobs=held, staging_restored=False,
            capacity_approvals_enabled=False, capacity_waiters_held=True,
            cloud_resources_may_still_bill=True))
        _sync_directory(target)
        return {"state": "restored_isolated", "objects": len(manifest["objects"]), "held_jobs": len(held),
                "authentication": "must_reprovision", "execution_enabled": False}
    except Exception:
        raise BackupError("restore_failed_new_directory_kept_for_review") from None


def _postgres_environment(url_file, *, private_platform_network=False):
    """Private process-only connection values; never print or serialize them."""
    secret = _regular(url_file, max_bytes=16384)
    try:
        with secret.open("rb") as handle:
            info = os.fstat(handle.fileno())
            if (not stat.S_ISREG(info.st_mode) or info.st_nlink != 1
                    or os.name != "nt" and info.st_mode & (stat.S_IRWXO | stat.S_IWGRP)):
                raise ValueError
            raw = handle.read(16385)
            if len(raw) > 16384:
                raise ValueError
        value = raw.decode("utf-8").removesuffix("\n").removesuffix("\r")
        parsed = urlsplit(value.replace("postgresql+psycopg://", "postgresql://", 1))
        if (parsed.scheme != "postgresql" or not all((parsed.hostname, parsed.port, parsed.username, parsed.password))
                or not re.fullmatch(r"/[A-Za-z_][A-Za-z0-9_]{0,62}", parsed.path) or parsed.fragment
                or any(c in value for c in ("\n", "\r", "\x00")) or value != value.strip()
                or not re.fullmatch(r"[A-Za-z0-9.:-]+", parsed.hostname)):
            raise ValueError
        options = parse_qs(parsed.query, strict_parsing=True)
        if set(options)-{"sslmode", "sslrootcert"} or any(len(values) != 1 for values in options.values()):
            raise ValueError
        sslmode = options.get("sslmode", [""])[0]
        if type(private_platform_network) is not bool:
            raise ValueError
        if private_platform_network:
            # Operator opt-in for this repository's exact private Compose DB.
            # Never silently infer that an arbitrary remote hostname is safe.
            if ((parsed.hostname, parsed.port, unquote(parsed.username), parsed.path) !=
                    ("db", 5432, "sixnine_app", "/sixnine") or parsed.query):
                raise ValueError
            sslmode = "disable"
        if not sslmode:
            if parsed.hostname not in {"127.0.0.1", "localhost", "::1"}:
                raise ValueError
            sslmode = "disable"
        if sslmode not in {"disable", "verify-full"}:
            raise ValueError
        # An explicit URL query is not proof of a private network. Only the
        # reviewed Compose opt-in above or literal loopback may use plaintext;
        # otherwise a copied DSN could silently send the password off-host.
        if (sslmode == "disable" and not private_platform_network
                and parsed.hostname not in {"127.0.0.1", "localhost", "::1"}):
            raise ValueError
        env = {name: os.environ[name] for name in ("PATH", "SYSTEMROOT", "TEMP", "TMP") if name in os.environ}
        env.update(PGHOST=parsed.hostname, PGPORT=str(parsed.port), PGUSER=unquote(parsed.username),
                   PGPASSWORD=unquote(parsed.password), PGDATABASE=parsed.path[1:], PGSSLMODE=sslmode,
                   PGCONNECT_TIMEOUT="10", PGAPPNAME="sixnine-backup")
        if "sslrootcert" in options:
            env["PGSSLROOTCERT"] = str(_regular(options["sslrootcert"][0]))
    except Exception:
        raise BackupError("backup_database_url_invalid_or_not_explicit") from None
    return env


def backup_postgres_local(url_file, object_root, destination, *, schema="public", max_media_bytes=40*1024*MIB,
                          private_platform_network=False):
    """Explicit protected DSN file; no admin rights, pg_dump, or source writes."""
    env = _postgres_environment(url_file, private_platform_network=private_platform_network)
    query = {"sslmode": env["PGSSLMODE"]}
    if "PGSSLROOTCERT" in env:
        query["sslrootcert"] = env["PGSSLROOTCERT"]
    url = URL.create("postgresql+psycopg", username=env["PGUSER"], password=env["PGPASSWORD"],
        host=env["PGHOST"], port=int(env["PGPORT"]), database=env["PGDATABASE"], query=query)
    engine = create_engine(url, echo=False, hide_parameters=True,
        connect_args={"connect_timeout": 10, "application_name": "sixnine-backup"})
    try:
        return backup_postgres_engine(engine, object_root, destination, schema=schema, max_media_bytes=max_media_bytes)
    finally:
        engine.dispose()


def dump_postgres(url_file, destination, *, pg_dump="pg_dump", schema="public", timeout_s=600):
    """Database-only explicit tool, not a verified full media backup/PG restore.

    Password stays in the child environment; no DSN/password is placed in argv,
    output, logs, or backup. Do not invoke except for an authorized DB operation.
    """
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]{0,62}", schema):
        raise BackupError("backup_schema_invalid")
    env = _postgres_environment(url_file)
    output = _private_new_directory(destination)
    command = [str(pg_dump), "--format=custom", "--no-owner", "--no-acl", "--no-password", "--no-blobs",
               "--strict-names", "--file="+str(output/"database.dump")]
    command += ["--table="+schema+"."+name for name in sorted(_tables())]
    try:
        subprocess.run(command, env=env, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL, timeout=timeout_s, check=True,
                       creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0)
        archive = _regular(output/"database.dump")
        if not archive.stat().st_size:
            raise BackupError("backup_postgres_dump_empty")
        if os.name != "nt":
            archive.chmod(0o600)
        _write_json(output/"manifest.json", dict(version=1, kind="postgres-database-only",
            database_sha256=_digest(archive), media_included=False, restore_verified=False,
            authentication_included=False, created_at=time.time()))
        return {"state": "postgres_database_dumped", "media_included": False, "restore_verified": False}
    except Exception:
        raise BackupError("backup_postgres_dump_failed_no_secret_output") from None
