"""Build a deterministic frontend artifact from a clean Vite output directory."""
from __future__ import annotations

import argparse
import gzip
import io
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from deploy.platform import frontend_bundle as bundle


def build(commit, dist, destination):
    bundle.require(isinstance(commit, str) and bundle.SHA.fullmatch(commit), "frontend_exact_commit_required")
    source = bundle.directory(dist)
    children = {child.name: child for child in source.iterdir()}
    bundle.require(set(children) == {"index.html", "assets"}, "frontend_dist_must_only_contain_index_and_assets")
    asset_dir = bundle.directory(children["assets"])
    entries = [("index.html", children["index.html"])]
    for path in sorted(asset_dir.iterdir()):
        name = "assets/" + path.name
        bundle.require(bundle.allowed_name(name), "frontend_dist_asset_name_invalid")
        entries.append((name, path))
    bundle.require(len(entries) <= bundle.MAX_FILES, "frontend_file_count_limit")
    content, metadata, total, folded = {}, {}, 0, set()
    for name, path in entries:
        bundle.require(name.casefold() not in folded, "frontend_dist_name_collision")
        folded.add(name.casefold())
        raw = bundle.read_regular(path, bundle.MAX_INDEX if name == "index.html" else bundle.MAX_FILE)
        bundle.require(bool(raw), "frontend_dist_empty_file")
        total += len(raw)
        bundle.require(total <= bundle.MAX_EXPANDED, "frontend_expansion_limit")
        content[name] = raw
        metadata[name] = {"sha256": bundle.digest(raw), "size": len(raw)}
    archive_buffer = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=archive_buffer, mtime=0) as compressed:
        tar_size = 0
        for name in sorted(content):
            raw = content[name]
            compressed.write(bundle.tar_header(name, len(raw)))
            compressed.write(raw)
            padding = (-len(raw)) % 512
            compressed.write(bytes(padding))
            tar_size += 512 + len(raw) + padding
        compressed.write(bytes(1024))
        compressed.write(bytes((-(tar_size + 1024)) % 10240))
    archive = archive_buffer.getvalue()
    bundle.require(len(archive) <= bundle.MAX_ARCHIVE, "frontend_archive_size_invalid")
    # The API source compatibility identity is generated by the shared release contract.
    from tools.release_contract import build_contracts
    compatibility = build_contracts(ROOT)["api_compatibility"]
    manifest = {"version": 1, "commit": commit, "api_contract": bundle.API_CONTRACT,
        "api_compatibility": compatibility, "archive_sha256": bundle.digest(archive),
        "archive_bytes": len(archive), "files": metadata}
    manifest_raw = (json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")
    bundle.parse_manifest(manifest_raw, commit)
    bundle.unpack_verified(archive, manifest)
    target = Path(destination)
    target.mkdir(parents=True, exist_ok=True)
    bundle.directory(target)
    bundle.require(not any(target.iterdir()), "frontend_destination_must_be_empty")
    # Exclusive creation never replaces an earlier bundle or an operator file.
    with (target / bundle.ARCHIVE_NAME).open("xb") as output:
        output.write(archive)
    with (target / bundle.MANIFEST_NAME).open("xb") as output:
        output.write(manifest_raw)
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("commit")
    parser.add_argument("dist", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    try:
        value = build(args.commit, args.dist, args.destination)
    except Exception:
        print("Frontend bundle build failed; no publication was requested", file=sys.stderr)
        return 1
    print(json.dumps({"commit": value["commit"], "files": len(value["files"]),
                      "archive_sha256": value["archive_sha256"], "status": "built"}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
